---
kind: pipeline
name: Deploy

trigger:
  event:
    include:
      - tag
      - push
  branch:
    - master

steps:
  - name: Install js packages
    image: node:16
    volumes:
      - name: node_cache
        path: /tmp
    commands:
      - yarn config set cache-folder /tmp
      - yarn

  - name: Build assets
    image: node:16
    commands:
      - yarn build
    depends_on:
      - Install js packages

  - name: Upload assets
    image: robvankeilegom/ssh-rsync
    environment:
      SSH_KEY:
        from_secret: drone_ssh_key
      SSH_USER:
        from_secret: drone_ssh_user
      SSH_PORT:
        from_secret: drone_ssh_port
    commands:
      - eval `ssh-agent -s`
      - echo "$SSH_KEY" | ssh-add -
      - mkdir -p ~/.ssh && touch ~/.ssh/known_hosts
      - ssh-keyscan -p $SSH_PORT apache-conf-generator.robvankeilegom.be >> ~/.ssh/known_hosts
      - |
        rsync -av \
        -e "ssh -p $SSH_PORT" \
        /drone/src/dist/apache-conf-generator/ \
        $SSH_USER@apache-conf-generator.robvankeilegom.be:~/websites/apache-conf-generator.robvankeilegom.be/current/
    depends_on:
      - Build assets
